import type { Config } from 'tailwindcss'
import tailwindAnimate from 'tailwindcss-animate'

export default {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        // Design system semantic tokens — dark-mode first palette
        surface: 'hsl(var(--color-bg-surface))',
        elevated: 'hsl(var(--color-bg-elevated))',
        'border-subtle': 'hsl(var(--color-border-subtle))',
        'border-default': 'hsl(var(--color-border-default))',
        'text-primary': 'hsl(var(--color-text-primary))',
        'text-secondary': 'hsl(var(--color-text-secondary))',
        'text-muted': 'hsl(var(--color-text-muted))',
        brand: {
          accent: 'hsl(var(--color-brand-accent))',
          lime: 'hsl(var(--color-brand-lime))',
        },
        state: {
          error: 'hsl(var(--color-state-error))',
          success: 'hsl(var(--color-state-success))',
          warning: 'hsl(var(--color-state-warning))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['DM Serif Display', 'serif'],
        mono: ['DM Mono', 'monospace'],
      },
      fontSize: {
        'display-hero': ['72px', { lineHeight: '1.06' }],
        'display-hero-italic': ['72px', { lineHeight: '1.06' }],
        'heading-1': ['48px', { lineHeight: '1.08' }],
        'heading-2': ['32px', { lineHeight: '1.13' }],
        'heading-3': ['24px', { lineHeight: '1.25' }],
        'body-large': ['18px', { lineHeight: '1.56' }],
        'body-default': ['16px', { lineHeight: '1.5' }],
        'body-small': ['13px', { lineHeight: '1.33' }],
        'label-mono-default': ['13px', { lineHeight: '1.38' }],
        'label-mono-caps': ['11px', { lineHeight: '1.45' }],
        'label-mono-small': ['10px', { lineHeight: '1.4' }],
      },
      borderRadius: {
        DEFAULT: '8px',
        pill: '999px',
        lg: '8px',
        md: '6px',
        sm: '4px',
      },
      boxShadow: {
        'elevation-1': '0 1px 2px rgba(0,0,0,0.04)',
        'elevation-2': '0 2px 8px rgba(0,0,0,0.08)',
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        14: '56px',
        16: '64px',
        18: '72px',
        20: '80px',
      },
      screens: {
        sm: '375px',
        md: '768px',
        lg: '1280px',
        xl: '1440px',
      },
    },
  },
  plugins: [tailwindAnimate],
} satisfies Config
